data:
  trading_days: 5
  image_resolution: 32
  price_proportion: 0.75
  batch_size: 32
  num_images_train: 20_000
  num_images_valid: 1_000
  num_images_test: 20_000
model:
  name: 32x15
optimiser:
  lr: 1e-5
  wd: 0
